apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: ${NAMESPACE}
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: debug

    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members: []

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 1h
      chunk_retain_period: 30m

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    limits_config:
      metric_aggregation_enabled: true

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    pattern_ingester:
      enabled: true
      metric_aggregation:
        loki_address: localhost:3100

    ruler:
      alertmanager_url: http://localhost:9093

    frontend:
      encoding: protobuf

