apiVersion: batch/v1
kind: CronJob
metadata:
  name: gateway-rotate-keys
  namespace: ${NAMESPACE}
spec:
  concurrencyPolicy: Forbid
  schedule: "0 12 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gateway-rotate-keys-service-account
          restartPolicy: Never
          containers:
            - name: monsters-gateway
              image: ${REGISTRY_URL}/monsters/monsters-gateway:latest
              imagePullPolicy: Always
              command:
                - '/bin/sh'
                - '-c'
                - |
                  NODE_ENV=${NODE_ENV} /usr/local/bin/node ./build/src/tools/rotateKeys.js
