apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "R.bY#Mq$HJ%nAS=jP(DkLC<uW+zs7c3T[xN{2"
            - name: MYSQL_PASSWORD
              value: "R.bY#Mq$HJ%nAS=jP(DkLC<uW+zs7c3T[xN{2"
            - name: MYSQL_USER
              value: virus
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
      volumes:
        - name: mysql-volume
