apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel
  name: otel
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
        - name: otel
          image: otel/opentelemetry-collector-contrib:latest
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9090
            - containerPort: 8888
          volumeMounts:
            - name: otel-config-volume
              mountPath: /etc/otelcol-contrib
              readOnly: true
      volumes:
        - name: otel-config-volume
          configMap:
            name: otel-config

