apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit-mq
  name: rabbit-mq
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rabbit-mq
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
      - image: rabbitmq:latest
        imagePullPolicy: Always
        name: rabbit-mq
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "${RABBIT_CLIENT}" 
        - name: RABBITMQ_DEFAULT_PASS
          value: "${RABBIT_PASSWORD}"
        volumeMounts:
          - name: rabbit-volume
            mountPath: /var/lib/rabbitmq
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rabbit-volume
          persistentVolumeClaim:
            claimName: rabbit-pvc
