apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authorizations-rotate-keys-role
  namespace: ${NAMESPACE}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["monsters-authorizations"]
    verbs: ["get", "patch"]
