apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel
  name: otel
  namespace: ${NAMESPACE}
spec:
  selector:
    app: otel
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: prometheus-metrics
      protocol: TCP
      port: 9090
      targetPort: 9090

