apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
  namespace: default
spec:
  selector:
    app: rabbit-mq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
