apiVersion: apps/v1
kind: Deployment
metadata:
  name: monsters-authorizations
  namespace: default
  labels:
    app: monsters-authorizations
spec:
  progressDeadlineSeconds: 200
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: monsters-authorizations
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monsters-authorizations
    spec:
      containers:
        - name: monsters-authorizations
          image: ${REGISTRY_URL}/monsters/authorizations:latest
          imagePullPolicy: Always
          ports:
            - containerPort: ${PORTS_AUTHORIZATIONS_HTTP}
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "100M"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
            - mountPath: "/root/.cache/monsters"
              name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scripts
          hostPath:
            path: ${LOCATION_SCRIPTS}
        - name: logs
          hostPath:
            path: ${LOCATION_LOGS}
