apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monsters-fights
  name: monsters-fights
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: monsters-fights
  strategy:
    rollingUpdate:
      maxSurge: 100
      maxUnavailable: 50
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monsters-fights
    spec:
      containers:
        - image: localhost:5000/monsters/monsters-fights:latest
          imagePullPolicy: Always
          name: monsters-fights
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5003
            - containerPort: 5004
          resources:
            requests:
              cpu: 500m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
