apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monsters-messages
  name: monsters-messages
  namespace: default
spec:
  progressDeadlineSeconds: 200
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: monsters-messages
  strategy:
    rollingUpdate:
      maxSurge: 100
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monsters-messages
    spec:
      containers:
        - name: monsters-messages
          image: localhost:5000/monsters/monsters-messages:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scripts
          hostPath:
            path: /path/to/your/livenessProbe/location
