apiVersion: apps/v1
kind: Deployment
metadata:
  name: monsters-users
  namespace: default
  labels:
    app: monsters-users
spec:
  progressDeadlineSeconds: 200
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: monsters-users
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monsters-users
    spec:
      containers:
        - name: monsters-users
          image: ${REGISTRY_URL}/monsters/monsters-users:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "2000mb"
            requests:
              cpu: "0.5"
              memory: "100mb"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /scripts/livenessProbe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
            - mountPath: "/root/.cache/monsters"
              name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scripts
          hostPath:
            path: ${LOCATION_SCRIPTS}
        - name: logs
          hostPath:
            path: ${LOCATION_LOGS}
