apiVersion: v1
kind: Service
metadata:
  name: monsters-authorizations-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: monsters-authorizations
  ports:
    - name: http
      port: ${PORTS_AUTHORIZATIONS_HTTP}
      targetPort: ${PORTS_AUTHORIZATIONS_HTTP}
