apiVersion: v1
kind: Service
metadata:
  name: monsters-gateway-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: monsters-gateway
  ports:
    - name: http
      port: 5003
      targetPort: 5003
    - name: websocket
      port: 5004
      targetPort: 5004
