apiVersion: v1
kind: Service
metadata:
  name: monsters-gateway-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: monsters-gateway
  ports:
    - name: http
      port: ${PORTS_GATEWAY_HTTP}
      targetPort: ${PORTS_GATEWAY_HTTP}
    - name: websocket
      port: ${PORTS_GATEWAY_SOCKET}
      targetPort: ${PORTS_GATEWAY_SOCKET}
