apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: ${NAMESPACE}
spec:
  storageClassName: ""
  volumeName: loki-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE_LOKI}Gi
