apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: default
spec:
  volumeName: mongo-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi