apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  volumeName: mysql-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi