apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: ${VOLUME_SIZE_PROMETHEUS}Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${PROMETHEUS_PV}
