apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: ${NAMESPACE}
spec:
  storageClassName: ""
  volumeName: prometheus-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE_PROMETHEUS}Gi
