apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvc
  namespace: default
spec:
  storageClassName: "" 
  volumeName: rabbit-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE_RABBIT}Gi
