apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
spec:
  storageClassName: ""
  volumeName: redis-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE_REDIS}Gi
